onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -format Analog-Step -height 74 -max 254.99999999999997 -radix sfixed -childformat {{{/FFT_tb/fft_inst/x_real[15]} -radix sfixed} {{/FFT_tb/fft_inst/x_real[14]} -radix sfixed} {{/FFT_tb/fft_inst/x_real[13]} -radix sfixed} {{/FFT_tb/fft_inst/x_real[12]} -radix sfixed} {{/FFT_tb/fft_inst/x_real[11]} -radix sfixed} {{/FFT_tb/fft_inst/x_real[10]} -radix sfixed} {{/FFT_tb/fft_inst/x_real[9]} -radix sfixed} {{/FFT_tb/fft_inst/x_real[8]} -radix sfixed} {{/FFT_tb/fft_inst/x_real[7]} -radix sfixed} {{/FFT_tb/fft_inst/x_real[6]} -radix sfixed} {{/FFT_tb/fft_inst/x_real[5]} -radix sfixed} {{/FFT_tb/fft_inst/x_real[4]} -radix sfixed} {{/FFT_tb/fft_inst/x_real[3]} -radix sfixed} {{/FFT_tb/fft_inst/x_real[2]} -radix sfixed} {{/FFT_tb/fft_inst/x_real[1]} -radix sfixed} {{/FFT_tb/fft_inst/x_real[0]} -radix sfixed}} -subitemconfig {{/FFT_tb/fft_inst/x_real[15]} {-height 15 -radix sfixed} {/FFT_tb/fft_inst/x_real[14]} {-height 15 -radix sfixed} {/FFT_tb/fft_inst/x_real[13]} {-height 15 -radix sfixed} {/FFT_tb/fft_inst/x_real[12]} {-height 15 -radix sfixed} {/FFT_tb/fft_inst/x_real[11]} {-height 15 -radix sfixed} {/FFT_tb/fft_inst/x_real[10]} {-height 15 -radix sfixed} {/FFT_tb/fft_inst/x_real[9]} {-height 15 -radix sfixed} {/FFT_tb/fft_inst/x_real[8]} {-height 15 -radix sfixed} {/FFT_tb/fft_inst/x_real[7]} {-height 15 -radix sfixed} {/FFT_tb/fft_inst/x_real[6]} {-height 15 -radix sfixed} {/FFT_tb/fft_inst/x_real[5]} {-height 15 -radix sfixed} {/FFT_tb/fft_inst/x_real[4]} {-height 15 -radix sfixed} {/FFT_tb/fft_inst/x_real[3]} {-height 15 -radix sfixed} {/FFT_tb/fft_inst/x_real[2]} {-height 15 -radix sfixed} {/FFT_tb/fft_inst/x_real[1]} {-height 15 -radix sfixed} {/FFT_tb/fft_inst/x_real[0]} {-height 15 -radix sfixed}} /FFT_tb/fft_inst/x_real
add wave -noupdate -format Analog-Step -height 74 -max 254.99999999999997 -radix sfixed -childformat {{{/FFT_tb/fft_inst/y_imag[15]} -radix sfixed} {{/FFT_tb/fft_inst/y_imag[14]} -radix sfixed} {{/FFT_tb/fft_inst/y_imag[13]} -radix sfixed} {{/FFT_tb/fft_inst/y_imag[12]} -radix sfixed} {{/FFT_tb/fft_inst/y_imag[11]} -radix sfixed} {{/FFT_tb/fft_inst/y_imag[10]} -radix sfixed} {{/FFT_tb/fft_inst/y_imag[9]} -radix sfixed} {{/FFT_tb/fft_inst/y_imag[8]} -radix sfixed} {{/FFT_tb/fft_inst/y_imag[7]} -radix sfixed} {{/FFT_tb/fft_inst/y_imag[6]} -radix sfixed} {{/FFT_tb/fft_inst/y_imag[5]} -radix sfixed} {{/FFT_tb/fft_inst/y_imag[4]} -radix sfixed} {{/FFT_tb/fft_inst/y_imag[3]} -radix sfixed} {{/FFT_tb/fft_inst/y_imag[2]} -radix sfixed} {{/FFT_tb/fft_inst/y_imag[1]} -radix sfixed} {{/FFT_tb/fft_inst/y_imag[0]} -radix sfixed}} -subitemconfig {{/FFT_tb/fft_inst/y_imag[15]} {-height 15 -radix sfixed} {/FFT_tb/fft_inst/y_imag[14]} {-height 15 -radix sfixed} {/FFT_tb/fft_inst/y_imag[13]} {-height 15 -radix sfixed} {/FFT_tb/fft_inst/y_imag[12]} {-height 15 -radix sfixed} {/FFT_tb/fft_inst/y_imag[11]} {-height 15 -radix sfixed} {/FFT_tb/fft_inst/y_imag[10]} {-height 15 -radix sfixed} {/FFT_tb/fft_inst/y_imag[9]} {-height 15 -radix sfixed} {/FFT_tb/fft_inst/y_imag[8]} {-height 15 -radix sfixed} {/FFT_tb/fft_inst/y_imag[7]} {-height 15 -radix sfixed} {/FFT_tb/fft_inst/y_imag[6]} {-height 15 -radix sfixed} {/FFT_tb/fft_inst/y_imag[5]} {-height 15 -radix sfixed} {/FFT_tb/fft_inst/y_imag[4]} {-height 15 -radix sfixed} {/FFT_tb/fft_inst/y_imag[3]} {-height 15 -radix sfixed} {/FFT_tb/fft_inst/y_imag[2]} {-height 15 -radix sfixed} {/FFT_tb/fft_inst/y_imag[1]} {-height 15 -radix sfixed} {/FFT_tb/fft_inst/y_imag[0]} {-height 15 -radix sfixed}} /FFT_tb/fft_inst/y_imag
add wave -noupdate /FFT_tb/fft_inst/state
add wave -noupdate -color Magenta /FFT_tb/fft_inst/count
add wave -noupdate -color Gold -format Analog-Step -height 74 -max 16319.999999999998 -radix sfixed -childformat {{{/FFT_tb/fft_inst/fft_real[15]} -radix sfixed} {{/FFT_tb/fft_inst/fft_real[14]} -radix sfixed} {{/FFT_tb/fft_inst/fft_real[13]} -radix sfixed} {{/FFT_tb/fft_inst/fft_real[12]} -radix sfixed} {{/FFT_tb/fft_inst/fft_real[11]} -radix sfixed} {{/FFT_tb/fft_inst/fft_real[10]} -radix sfixed} {{/FFT_tb/fft_inst/fft_real[9]} -radix sfixed} {{/FFT_tb/fft_inst/fft_real[8]} -radix sfixed} {{/FFT_tb/fft_inst/fft_real[7]} -radix sfixed} {{/FFT_tb/fft_inst/fft_real[6]} -radix sfixed} {{/FFT_tb/fft_inst/fft_real[5]} -radix sfixed} {{/FFT_tb/fft_inst/fft_real[4]} -radix sfixed} {{/FFT_tb/fft_inst/fft_real[3]} -radix sfixed} {{/FFT_tb/fft_inst/fft_real[2]} -radix sfixed} {{/FFT_tb/fft_inst/fft_real[1]} -radix sfixed} {{/FFT_tb/fft_inst/fft_real[0]} -radix sfixed}} -subitemconfig {{/FFT_tb/fft_inst/fft_real[15]} {-color Gold -height 15 -radix sfixed} {/FFT_tb/fft_inst/fft_real[14]} {-color Gold -height 15 -radix sfixed} {/FFT_tb/fft_inst/fft_real[13]} {-color Gold -height 15 -radix sfixed} {/FFT_tb/fft_inst/fft_real[12]} {-color Gold -height 15 -radix sfixed} {/FFT_tb/fft_inst/fft_real[11]} {-color Gold -height 15 -radix sfixed} {/FFT_tb/fft_inst/fft_real[10]} {-color Gold -height 15 -radix sfixed} {/FFT_tb/fft_inst/fft_real[9]} {-color Gold -height 15 -radix sfixed} {/FFT_tb/fft_inst/fft_real[8]} {-color Gold -height 15 -radix sfixed} {/FFT_tb/fft_inst/fft_real[7]} {-color Gold -height 15 -radix sfixed} {/FFT_tb/fft_inst/fft_real[6]} {-color Gold -height 15 -radix sfixed} {/FFT_tb/fft_inst/fft_real[5]} {-color Gold -height 15 -radix sfixed} {/FFT_tb/fft_inst/fft_real[4]} {-color Gold -height 15 -radix sfixed} {/FFT_tb/fft_inst/fft_real[3]} {-color Gold -height 15 -radix sfixed} {/FFT_tb/fft_inst/fft_real[2]} {-color Gold -height 15 -radix sfixed} {/FFT_tb/fft_inst/fft_real[1]} {-color Gold -height 15 -radix sfixed} {/FFT_tb/fft_inst/fft_real[0]} {-color Gold -height 15 -radix sfixed}} /FFT_tb/fft_inst/fft_real
add wave -noupdate -color Cyan -format Analog-Step -height 74 -max 16319.999999999998 -radix sfixed -childformat {{{/FFT_tb/fft_inst/fft_imag[15]} -radix sfixed} {{/FFT_tb/fft_inst/fft_imag[14]} -radix sfixed} {{/FFT_tb/fft_inst/fft_imag[13]} -radix sfixed} {{/FFT_tb/fft_inst/fft_imag[12]} -radix sfixed} {{/FFT_tb/fft_inst/fft_imag[11]} -radix sfixed} {{/FFT_tb/fft_inst/fft_imag[10]} -radix sfixed} {{/FFT_tb/fft_inst/fft_imag[9]} -radix sfixed} {{/FFT_tb/fft_inst/fft_imag[8]} -radix sfixed} {{/FFT_tb/fft_inst/fft_imag[7]} -radix sfixed} {{/FFT_tb/fft_inst/fft_imag[6]} -radix sfixed} {{/FFT_tb/fft_inst/fft_imag[5]} -radix sfixed} {{/FFT_tb/fft_inst/fft_imag[4]} -radix sfixed} {{/FFT_tb/fft_inst/fft_imag[3]} -radix sfixed} {{/FFT_tb/fft_inst/fft_imag[2]} -radix sfixed} {{/FFT_tb/fft_inst/fft_imag[1]} -radix sfixed} {{/FFT_tb/fft_inst/fft_imag[0]} -radix sfixed}} -subitemconfig {{/FFT_tb/fft_inst/fft_imag[15]} {-color Cyan -height 15 -radix sfixed} {/FFT_tb/fft_inst/fft_imag[14]} {-color Cyan -height 15 -radix sfixed} {/FFT_tb/fft_inst/fft_imag[13]} {-color Cyan -height 15 -radix sfixed} {/FFT_tb/fft_inst/fft_imag[12]} {-color Cyan -height 15 -radix sfixed} {/FFT_tb/fft_inst/fft_imag[11]} {-color Cyan -height 15 -radix sfixed} {/FFT_tb/fft_inst/fft_imag[10]} {-color Cyan -height 15 -radix sfixed} {/FFT_tb/fft_inst/fft_imag[9]} {-color Cyan -height 15 -radix sfixed} {/FFT_tb/fft_inst/fft_imag[8]} {-color Cyan -height 15 -radix sfixed} {/FFT_tb/fft_inst/fft_imag[7]} {-color Cyan -height 15 -radix sfixed} {/FFT_tb/fft_inst/fft_imag[6]} {-color Cyan -height 15 -radix sfixed} {/FFT_tb/fft_inst/fft_imag[5]} {-color Cyan -height 15 -radix sfixed} {/FFT_tb/fft_inst/fft_imag[4]} {-color Cyan -height 15 -radix sfixed} {/FFT_tb/fft_inst/fft_imag[3]} {-color Cyan -height 15 -radix sfixed} {/FFT_tb/fft_inst/fft_imag[2]} {-color Cyan -height 15 -radix sfixed} {/FFT_tb/fft_inst/fft_imag[1]} {-color Cyan -height 15 -radix sfixed} {/FFT_tb/fft_inst/fft_imag[0]} {-color Cyan -height 15 -radix sfixed}} /FFT_tb/fft_inst/fft_imag
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {29740 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 203
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 fs} {248398500 ps}
